name: build
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ 1, 1.14, 1.15 ]
    steps:
      - uses: actions/checkout@v2
      - name: set image tag
        run: |
          echo "::set-env name=IMAGE_NAME::ghcr.io/willabides/codespaces-go${{ matrix.go-version }}:${{ github.sha }}"
          echo "::set-env name=LATEST_TAG::ghcr.io/willabides/codespaces-go${{ matrix.go-version }}:latest"
          echo "::set-env name=IMAGE_GO_VERSION::${{ matrix.go-version }}"
      - name: docker login
        run: echo "${{ secrets.WILLABIDES_TOKEN }}" | docker login ghcr.io --username gh-containers-bot --password-stdin
      - run: script/build
      - name: push sha tag
        run: docker push "$IMAGE_NAME"
      - name: push latest tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag "$IMAGE_NAME" "$LATEST_TAG"
          docker push "$LATEST_TAG"
